name: Continous Integration for my Next.js Apps

on:
  push:
    branches:
      - main
      - master
    pull_request:
      branches:
        - main
        - master

  jobs:
    ci:
      runs-on: ${{matrix.os}}

      strategy:
        matrix:
          os: [ubuntu-latest]
          node: [16]

      steps:
        - name: Checkout 🛎
          uses: actions/checkout@master

        - name: Setup node env 🏗
          uses: actions/setup-node@v2.1.5
          with:
            node-version: ${{ matrix.node }}
            check-latest: true

        - name: Get yarn cache directory path 🛠
          id: yarn-cache-dir-path
          run: echo "::set-output node=dir::${yarn cache dir}"

        - name: Cache node_modules 📦
          uses: actions/cache@v2.1.4
          id: yarn-cache
          with:
            path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-

        - name: Install dependencies 👨🏻‍💻
          run: yarn
